# Generated by Django 5.2.1 on 2025-05-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contac_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='checked',
        ),
    ]
