# Generated by Django 5.2.1 on 2025-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('art', models.ImageField(upload_to='static/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
