# Generated by Django 5.2.1 on 2025-05-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='art',
            field=models.ImageField(upload_to=''),
        ),
    ]
