# Generated by Django 5.2.1 on 2025-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='art',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
